name: API test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch workflow
        run: |
          curl -X POST \
          -u "${{ secrets.USERNAME }}:${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          --data '{"event_type": "Build 1st batch of wheels"}' \
          "https://api.github.com/repos/rara64/armv5-homeassistant/dispatches"
