name: Build base image for armv5-homeassistant

concurrency: 
  group: my-workflow-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push the image
        run: |
          docker buildx build --push --file Dockerfile.base \
            --tag rara64/armv5-debian-base:latest --label version="1.0.0" \
            --platform linux/arm/v5 --allow security.insecure --no-cache
