name: Build armv5-homeassistant

on: 
  schedule:
    - cron: '32 1 * * MON'
  workflow_dispatch:
  repository_dispatch:
    types: Build armv5-homeassistant
  
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check for new release of Home Assistant
        run: |
          export HASS_RELEASE=$(jq -r 'map(select(.prerelease==false)) | first | .tag_name' <<< $(curl --silent https://api.github.com/repos/home-assistant/core/releases))
          export ARMV5_RELEASE=$(jq -r '[.results[] | select(.name!="latest")][0].name' <<< $(curl --silent https://hub.docker.com/v2/repositories/rara64/armv5-homeassistant/tags/?page_size=1000))
          echo "HASS_RELEASE=$HASS_RELEASE" >> $GITHUB_ENV
          echo "ARMV5_RELEASE=$ARMV5_RELEASE" >> $GITHUB_ENV
          echo "HASS_RELEASE: $HASS_RELEASE , ARMV5_RELEASE: $ARMV5_RELEASE"

      - name: Checkout code
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE }}
        uses: actions/checkout@v6

      - name: Check version of go2rtc
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE }}
        env:
          WHEELS_TOKEN: ${{ secrets.WHEELS_TOKEN }}
        run: |
          chmod +x ./.github/scripts/go2rtc.sh
          ./.github/scripts/go2rtc.sh ${{ env.HASS_RELEASE }}
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 3 ]; then
            curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build go2rtc for armv5-homeassistant"}'
            echo "OUTDATED=1" >> $GITHUB_ENV
          fi
          echo "OUTDATED=0" >> $GITHUB_ENV

      - name: Check version of python
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE && env.OUTDATED == '0' }}
        run: |
          chmod +x ./.github/scripts/python.sh
          ./.github/scripts/python.sh ${{ env.HASS_RELEASE }}
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 3 ]; then
            curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build base image for armv5-homeassistant"}'
            echo "OUTDATED=1" >> $GITHUB_ENV
          fi
          echo "OUTDATED=0" >> $GITHUB_ENV

      - name: Check version of maturin
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE && env.OUTDATED == '0' }}
        env:
          WHEELS_TOKEN: ${{ secrets.WHEELS_TOKEN }}
        run: |
          chmod +x ./.github/scripts/maturin.sh
          ./.github/scripts/maturin.sh
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 3 ]; then
            curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build maturin for armv5-homeassistant"}'
            echo "OUTDATED=1" >> $GITHUB_ENV
          fi
          echo "OUTDATED=0" >> $GITHUB_ENV

      - name: Check version of dependencies
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE && env.OUTDATED == '0' }}
        env:
          WHEELS_TOKEN: ${{ secrets.WHEELS_TOKEN }}
        run: |
          chmod +x ./.github/scripts/deps.sh
          ./.github/scripts/deps.sh ${{ env.HASS_RELEASE }}
          EXIT_CODE=$?

          if [ $EXIT_CODE -eq 3 ]; then
            curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build deps for armv5-homeassistant"}'
            echo "OUTDATED=1" >> $GITHUB_ENV
          fi
          echo "OUTDATED=0" >> $GITHUB_ENV

      - name: Set up QEMU
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE && env.OUTDATED == '0' }}
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm
          image: tonistiigi/binfmt:qemu-v8.1.5
          
      - name: Set up Docker Buildx
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE && env.OUTDATED == '0' }}
        uses: docker/setup-buildx-action@v4

      - name: Login to Docker Hub
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE && env.OUTDATED == '0' }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push the image
        if: ${{ env.HASS_RELEASE != env.ARMV5_RELEASE && env.OUTDATED == '0' }}
        run: |
          docker buildx build --push --platform linux/arm/v5 \
          --build-arg DEPS="./deps" \
          --build-arg GO2RTC="go2rtc/go2rtc_linux_armv5" \
          --tag rara64/armv5-homeassistant:${{ env.HASS_RELEASE }} \
          --tag rara64/armv5-homeassistant:latest --label version="${{ env.HASS_RELEASE }}" \
          --allow security.insecure --no-cache -f ./Dockerfile .
