name: Build 3rd batch of wheels

on:
  repository_dispatch:
    types: Build 3rd batch of wheels
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version for wheels
        shell: bash
        run: |
          export TAG=$(curl --silent https://api.github.com/repos/home-assistant/core/releases | jq -r 'map(select(.prerelease==false)) | first | .tag_name')
          export WHEELS_LIST=('ZEROCONF')
          export WHEELS_LIST_REQ=('ELEVENLABS' 'ANTHROPIC')
          
          for wheel in "${WHEELS_LIST[@]}"; do 
            export ${wheel}_VER=$(curl --silent "https://raw.githubusercontent.com/home-assistant/core/$TAG/homeassistant/package_constraints.txt" | grep -m 1 -i "${wheel}" | awk -F'=' '{print $NF}' | tr -d '\n')
          done

          for wheel in "${WHEELS_LIST_REQ[@]}"; do 
            export ${wheel}_VER=$(curl --silent "https://raw.githubusercontent.com/home-assistant/core/$TAG/requirements_all.txt" | grep -m 1 -i "${wheel}==" | awk -F'=' '{print $NF}' | tr -d '\n')
          done
          
          for wheel in "${WHEELS_LIST[@]}"; do w="${wheel}_VER"; echo "${wheel}_VER=${!w}" >> $GITHUB_ENV; done
          for wheel in "${WHEELS_LIST_REQ[@]}"; do w="${wheel}_VER"; echo "${wheel}_VER=${!w}" >> $GITHUB_ENV; done

          echo $ZEROCONF_VER
          echo $ANTHROPIC_VER
          echo $ELEVENLABS_VER
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and load the image
        run: |
          export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "wheels4") | .archive_download_url' | head -n 1)

          if [ -z "$LINK" ]; then
            echo "WHEELS_NEEDED=1" >> $GITHUB_ENV
            exit 0
          fi

          wget -O wheels4.zip $(curl -I -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" $LINK | grep location: | cut -d: -f2-)
          echo "WHEELS_NEEDED=0" >> $GITHUB_ENV
          
          docker buildx build --load --tag wheels -f wheels3/Dockerfile --build-arg MATURIN=wheels4.zip --build-arg ZEROCONF_VER=${{ env.ZEROCONF_VER }} --build-arg ANTHROPIC_VER=${{ env.ANTHROPIC_VER }} --build-arg ELEVENLABS_VER=${{ env.ELEVENLABS_VER }} --platform linux/arm/v5 --allow security.insecure --no-cache .
      - name: Build missing wheels4 if needed
        if: ${{ env.WHEELS_NEEDED == '1' }}
        run: |
          curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build 4th batch of wheels"}'  
      - name: Copy wheels from the image
        if: ${{ env.WHEELS_NEEDED == '0' }}
        shell: bash
        run: |
          docker create --name wheels wheels
          mkdir wheels
          docker cp wheels:./root/.cache/pip/wheels wheels
          
          export WHEELS_LIST=('ZEROCONF' 'JITER' 'PYDANTIC' 'TOKENIZERS' 'PYYAML')
          for wheel in "${WHEELS_LIST[@]}"; do export ${wheel}=$(find . -type f -name "*.whl" | grep -i "${wheel}"); done
          for wheel in "${WHEELS_LIST[@]}"; do w=${wheel}; echo "${wheel}=${!w}" >> $GITHUB_ENV; done

          echo "$ELEVENLABS_VER $ANTHROPIC_VER $ZEROCONF_VER" >> wheels3ver.txt
      - name: Upload wheels
        if: ${{ env.WHEELS_NEEDED == '0' }}
        uses: actions/upload-artifact@v3
        with:
          name: wheels3
          path: |
            ${{ env.ZEROCONF }}
            ${{ env.JITER }}
            ${{ env.PYDANTIC }}
            ${{ env.TOKENIZERS }}
            ${{ env.PYYAML }}
            ./wheels3ver.txt
      - name: Dispatch armv5-homeassistant
        if: ${{ env.WHEELS_NEEDED == '0' }}
        run: |
          curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build armv5-homeassistant"}'
