name: Build 2nd batch of armv5-homeassistant deps

concurrency: 
  group: my-workflow-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
  repository_dispatch:
    types: Build 2nd batch of armv5-homeassistant deps
  
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Find dependencies versions
        run: |
          export TAG=$(curl --silent https://api.github.com/repos/home-assistant/core/releases | jq -r 'map(select(.prerelease==false)) | first | .tag_name')
          wget https://raw.githubusercontent.com/home-assistant/core/$TAG/homeassistant/package_constraints.txt
          wget https://raw.githubusercontent.com/home-assistant/core/refs/tags/$TAG/requirements_all.txt
          cat *.txt >> reqs.txt
          sed '/^#/d' reqs.txt > filtered_reqs.txt
          mv filtered_reqs.txt reqs.txt
          export WHEELS_LIST=('ORJSON' 'PYNACL' 'ZEROCONF' 'DEEBOT' 'ELEVENLABS' 'ANTHROPIC')
          for wheel in "${WHEELS_LIST[@]}"; do 
            export ${wheel}_VER=$(cat reqs.txt | grep -m 1 -i "${wheel}" | awk -F'=' '{print $NF}' | tr -d '\n')
          done
          for wheel in "${WHEELS_LIST[@]}"; do w="${wheel}_VER"; echo "${wheel}_VER=${!w}" >> $GITHUB_ENV; done
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build deps
        run: |
          export DOCKER_BUILDKIT=0 
          sudo apt install -y qemu-user-static binfmt-support

          sudo update-binfmts --install armv5 /usr/bin/qemu-arm-static \
          --magic "\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00" \
          --mask "\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff" \
          --fix-binary yes

          uname -m

          export LINK=$(curl --silent https://api.github.com/repos/rara64/armv5-homeassistant/actions/artifacts | jq -r '.artifacts[] | select(.name == "deps") | .archive_download_url' | head -n 1)
          curl -L -H "Authorization: token ${{ secrets.WHEELS_TOKEN }}" -o deps.zip "$LINK" || echo 'deps download failed'

          docker buildx build --load --tag wheels \
          --build-arg ANTHROPIC_VER=${{ env.ANTHROPIC_VER }} \
          --build-arg DEEBOT_VER=${{ env.DEEBOT_VER }} \
          --build-arg ELEVENLABS_VER=${{ env.ELEVENLABS_VER }} \
          --build-arg ORJSON_VER=${{ env.ORJSON_VER }} \
          --build-arg PYNACL_VER=${{ env.PYNACL_VER }} \
          --build-arg ZEROCONF_VER=${{ env.ZEROCONF_VER }} \
          --build-arg DEPS="deps.zip" \
          --platform linux/arm/v5 --allow security.insecure --no-cache -f ./deps2/Dockerfile .
      - name: Extract wheels
        if: ${{ env.WHEELS_NEEDED == '0' }}
        shell: bash
        run: |
          docker create --name wheels wheels
          mkdir wheels
          docker cp wheels:./root/.cache/pip/wheels wheels
          echo "elevenlabs==${{ env.ELEVENLABS_VER }}" >> versions.txt
          echo "anthropic==${{env.ANTHROPIC_VER }}" >> versions.txt
      - name: Upload wheels
        if: ${{ env.WHEELS_NEEDED == '0' }}
        uses: actions/upload-artifact@v4
        with:
          name: deps2
          path: |
            ./wheels
      - name: Dispatch armv5-homeassistant on ARM
        if: ${{ env.WHEELS_NEEDED == '0' }}
        run: |
          sleep 90
          curl -XPOST -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.WHEELS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/rara64/armv5-homeassistant/dispatches --data '{"event_type": "Build armv5-homeassistant on ARM"}'
